version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    pull_policy: build
    image: kattungar-notify-server
    environment:
      - KATTUNGAR_STORE_PATH=/var/lib/sqlite/store.db
      - KATTUNGAR_APNS_KEY_ID
      - KATTUNGAR_APNS_KEY_PATH
      - KATTUNGAR_GOOGLE_CREDS_PATH
      - KATTUNGAR_GOOGLE_REFRESH_TOKEN
      - KATTUNGAR_GOOGLE_CALENDAR_ID
    ports:
      - "26002:5000"
    volumes:
      - dbdata:/var/lib/sqlite
      - secrets:/var/lib/secrets
volumes:
  dbdata:
  secrets:
